{
 "title": "FastAPI vs Spring",
 "description": "A comparison of FastAPI and Spring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory Usage (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{id=\"/docker/aac3d48df3ce41640cfbb5903cfa033c9c1265b3a27db2edee374c035ecc05a3\"} / 1024 / 1024",
     "legendFormat": "FastAPI"
    },
    {
     "expr": "container_memory_working_set_bytes{id=\"/docker/8cae3caf9312e7283c6355497a3b8a5e279c36d468882e7559155b64786860ab\"} / 1024 / 1024",
     "legendFormat": "Spring"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{id=\"/docker/aac3d48df3ce41640cfbb5903cfa033c9c1265b3a27db2edee374c035ecc05a3\"}[1m])",
     "legendFormat": "FastAPI"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{id=\"/docker/8cae3caf9312e7283c6355497a3b8a5e279c36d468882e7559155b64786860ab\"}[1m])",
     "legendFormat": "spring"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(job) (rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(job) (rate(http_server_requests_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P99 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_request_duration_seconds_bucket{handler!=\"/metrics\"}[1m])))",
     "legendFormat": "fastapi"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{uri!=\"/actuator/prometheus\"}[1m])))",
     "legendFormat": "spring"
    }
   ]
  }
 ]
}